### 1. Створюємо користувача (Отримає ID 1)
POST http://127.0.0.1:8000/api/players/
Content-Type: application/json

{
  "username": "NaviFan",
  "password": "super_password_123"
}

### 2. Створюємо матч: NAVI vs Vitality (Отримає ID 1)
POST http://127.0.0.1:8000/api/matches/
Content-Type: application/json

{
  "team1Name": "NAVI",
  "team2Name": "Vitality",
  "oddsTeam1": "1.85",
  "oddsTeam2": "2.10",
  "oddsDraw": "5.00"
}

### 3. Поповнюємо баланс юзеру на 1000
POST http://127.0.0.1:8000/api/users/1/top-up/
Content-Type: application/json

{
  "amount": "1000"
}

### 4. Робимо УСПІШНУ ставку (Ставимо 500 на перемогу першої команди)
POST http://127.0.0.1:8000/api/bets/place/
Content-Type: application/json

{
  "userId": 1,
  "matchId": 1,
  "amount": "500",
  "predictedResult": 1
}

### 5. ПЕРЕВІРКА ЗАХИСТУ (Намагаємося поставити 10 000, коли залишилося 500)
POST http://127.0.0.1:8000/api/bets/place/
Content-Type: application/json

{
  "userId": 1,
  "matchId": 1,
  "amount": "10000",
  "predictedResult": 2
}